### PR TITLE
Convert to OCaml

### PR DESCRIPTION
**Pull request by jfrolich**

### CODE REVIEW

**Comment by baransu** [comment]
Oh man, what a full circle it is 😮

**Comment by jfrolich** [comment]
> Oh man, what a full circle it is 😮

Yes it is! Given the situation with ReasonML I think this is the more stable path, and the ReScript core team would really like to see ppx's being written in pure OCaml. I also would like to split the repo in a native and ReScript version so I figured I do the conversion first, so it's easy to have cherry-pick improvements.

**Comment by anmonteiro** [comment]
There's a benefit of keeping both native and ReScript code together, as features won't deviate from one another. Am I misunderstanding the split and do you have a good solution for this in mind?

**Comment by jfrolich** [comment]
> There's a benefit of keeping both native and ReScript code together, as features won't deviate from one another. Am I misunderstanding the split and do you have a good solution for this in mind?

I want to use the rescript compiler hooks instead of `ppxlib`, that is the direction the ReScript team is going. Any idea how to do that while not splitting the codebase?

**Pull request merged**
